
jdbc_url: ${DB_JDBC:jdbc:postgresql://172.17.0.1:5432/account}
user_db: ${DB_USER:postgres}
pass_db: ${DB_PASSWORD:admin}
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    use-root-path: false
    path: /docs/swagger-ui.html
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /_app-state
  endpoint:
    health:
      show-details: always
      probes:
        add-additional-paths: true
        enabled: true
spring:
  profiles:
    active: ${PROFILE:dev}

  datasource:
    url: ${jdbc_url}
    username: ${user_db}
    password: ${pass_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


flyway:
  enabled: true
  url: ${jdbc_url}
  schemas: public
  username: ${user_db}
  password: ${pass_db}
  locations: classpath:db/migration
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true


