springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    use-root-path: false
    path: /docs/swagger-ui.html

spring:
  profiles:
    active: ${PROFILE:dev}

  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


flyway:
  enabled: true
  url: jdbc:postgresql://localhost:5432/account
  schemas: public
  username: postgres
  password: admin
  locations: classpath:db/migration
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true


