
jdbc_url: ${DB_JDBC:jdbc:postgresql://172.17.0.1:5432/account}
user_db: ${DB_USER:postgres}
pass_db: ${DB_PASSWORD:admin}

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    use-root-path: false
    path: /docs/swagger-ui.html
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /_app-state
  endpoint:
    health:
      show-details: always
      probes:
        add-additional-paths: true
        enabled: true
  server:
    port: 8081



spring:
  profiles:
    active: ${PROFILE:dev}

  datasource:
    testWhileIdle: true
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 3600000
    validationQuery: SELECT 1
    url: ${jdbc_url}
    username: ${user_db}
    password: ${pass_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: api
    password: api@user
    dynamic: true
    listener:
      simple:
        prefetch: 100

camel:
  springboot:
    auto-startup: true
    consumer-template-cache-size: 10
    producer-template-cache-size: 10
    main-run-controller: true
    name: AccountCamel
  component:
    spring-rabbitmq:
      auto-declare: true
flyway:
  enabled: true
  url: ${jdbc_url}
  schemas: public
  username: ${user_db}
  password: ${pass_db}
  locations: classpath:db/migration
server:
  port: ${PORT:8888}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true


events:
  origin:
    account-created: direct:accountCreated
    user-created: direct:userCreated
  destiny:
    rabbit-mq:
      account-created: spring-rabbitmq:account?routingKey=event.account.created&exchangeType=topic&autoDeclare=true
      user-created: spring-rabbitmq:account?routingKey=event.user.created&exchangeType=topic&autoDeclare=true
logging:
  level:
    root: INFO